# Generated by Django 4.1.7 on 2023-05-10 13:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club_name', models.CharField(max_length=100)),
                ('oib', models.CharField(max_length=11)),
                ('street', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('iban', models.CharField(max_length=35)),
                ('logo', models.ImageField(blank=True, upload_to='images/logos/')),
            ],
        ),
        migrations.CreateModel(
            name='MembershipFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='MembershipFeeType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('membership_fee', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oib', models.CharField(max_length=11)),
                ('birthday', models.DateField()),
                ('father_name', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, upload_to='images/players/')),
                ('access_card', models.ImageField(blank=True, upload_to='images/playersAccessCards/')),
                ('cartificate_of_nationality', models.ImageField(blank=True, upload_to='images/certificatesOfNationality/')),
                ('medical_examination', models.DateField(blank=True, null=True)),
                ('membership_fee_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='trainings.membershipfeetype')),
            ],
        ),
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birthday', models.DateField()),
                ('image', models.ImageField(blank=True, upload_to='images/trainers/')),
                ('club', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='trainings.club')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('training_duration', models.DecimalField(choices=[(1, '1h'), (1.5, '1.5h'), (2, '2h'), (2.5, '2.5h'), (3, '3h')], decimal_places=1, max_digits=2)),
                ('comment', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='TrainingHasPlayers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('presence', models.BooleanField()),
                ('absence_reason', models.CharField(blank=True, choices=[('Bez razloga', 'Bez razloga'), ('Škola', 'Škola'), ('Bolest', 'Bolest')], max_length=30)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='trainings.player')),
                ('training', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='trainings.training')),
            ],
            options={
                'unique_together': {('player', 'training')},
            },
        ),
        migrations.AddField(
            model_name='training',
            name='players',
            field=models.ManyToManyField(through='trainings.TrainingHasPlayers', to='trainings.player'),
        ),
        migrations.AddField(
            model_name='training',
            name='trainer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='trainings.trainer'),
        ),
        migrations.CreateModel(
            name='PlayersHasMembershipFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=5)),
                ('membership_fee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='trainings.membershipfee')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='trainings.player')),
            ],
        ),
        migrations.AddField(
            model_name='player',
            name='membership_fees',
            field=models.ManyToManyField(through='trainings.PlayersHasMembershipFee', to='trainings.membershipfee'),
        ),
        migrations.AddField(
            model_name='player',
            name='trainer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='trainings.trainer'),
        ),
        migrations.AddField(
            model_name='player',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
