# Generated by Django 4.1.7 on 2023-05-19 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='mobile',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='trainer',
            name='mobile',
            field=models.CharField(default='', max_length=30),
        ),
    ]
