# Generated by Django 4.1.7 on 2023-06-01 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0003_alter_player_mobile_alter_trainer_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='oib',
            field=models.CharField(max_length=11, unique=True),
        ),
    ]
