# Generated by Django 4.1.7 on 2023-06-20 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0004_alter_player_oib'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='replacement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='replacement_trainings', to='trainings.trainer'),
        ),
    ]
