# Generated by Django 4.1.7 on 2023-06-28 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0005_training_replacement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traininghasplayers',
            name='training',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainings.training'),
        ),
    ]
